 export const INCREMENT='INCREMENT';
 export const DECREMENT='DECREMENT';
 export const AUTODECREMENT='AUTODECREMENT';
 export const MANUALINCREMENT='MANUALINCREMENT';
 export const MANUALDECREMENT='MANUALDECREMENT';
 export const BREAKDECREMENT='BREAKDECREMENT';
 export const BREAKINCREMENT='BREAKINCREMENT';
 export const BREAKAUTODECREMENT='BREAKAUTODECREMENT';
 export const BREAKMANUALDECREMENT='BREAKMANUALDECREMENT';
 export const BREAKMANUALINCREMENT="BREAKMANUALINCREMENT";
 export const BREAKPOWER='BREAKPOWER';
 export const PAUSE="PAUSE";
 export const PLAY="PLAY";
 export const RESET='RESET';


